### ISSUE TITLE
Is this code applicable to handwritten Chinese character dataset？

### ISSUE THREAD

**Issue by wkw-creator** [thomasjhuang/deep-learning-for-document-dewarping#10]
I use the script to generate some distorted handwritten Chinese character data sets, and then modify the size of training and original image, but the effect is not good. Does the principle of this code apply to handwritten Chinese character data sets? If so, do you need to modify some parameters?

**Comment by thomasjhuang** [comment]
I'm not sure how this repository works on chinese character data sets. If you have some improvements or changes you would like to make. Feel free to submit a PR.
