### ISSUE TITLE
where is the weigths file?

### ISSUE THREAD

**Issue by yuyu0927** [thomasjhuang/deep-learning-for-document-dewarping#11]
Excuse me, when I run test.py, it reported "./checkpoints/kaggle/latest_net_G.pth not exists yet!".

**Comment by zbzzz** [comment]
您好，请问您解决了吗

**Comment by thomasjhuang** [comment]
Not included in the repo, please check previous PRs. If you want to add weights, feel free to submit a request and I will approve it.

**Comment by Testhjf** [comment]
can you share the pretrained model
