### ISSUE TITLE
No data folder

### ISSUE THREAD

**Issue by Enuvesta** [thomasjhuang/deep-learning-for-document-dewarping#4]
Hi! I have a bit of a struggle trying to reproduce training procedure. As I am aware, data folder is in gitignore file. I've tried to take the same folder from official pix2pix repository that you provided, but it didn't work. May be this is not due to data folder, but anyway help is appreciated

**Comment by thomasjhuang** [comment]
Try and put your content under /datasets and make a folder /trainA and /trainB. Hope this helps

**Comment by yl2019lw** [comment]
You didn't upload your data loader code.

**Comment by thomasjhuang** [comment]
Do you mean preprocess.py?

**Comment by yl2019lw** [comment]
In train.py, you have "from data.data_loader import CreateDataLoader", the code doesn't exist.

**Comment by DavidHoApoidea** [comment]
yes, I met the same issue.

**Comment by thomasjhuang** [comment]
My apologies, I'll take a look at the issue and once resolved I'll update this thread and the master branch

**Comment by thomasjhuang** [comment]
@rmporsch Resolved this issue. It's been a long time, I recently started a new job last year and things got really busy on my end. Sorry about the delay everyone, and I hope this repo is still of use. All credit due to @rmporsch
